//! Main Strings
const appname = "Smart Shopy",
    credits = "@pavin__das",
    appversion = "Version 1.0.0",

//! Home Strings
    Welcome = "Welcome",
    name = "Name",
    nameHint = "Your Name",
    email = "Email",
    phone = "Phone",
    phoneHint = "+91 9876543210",
    emailHint = "admin@admin.com",
    password = "Password",
    passwordHint = "******",
    retypepass = "Confirm Password",
    forgetPass = "Forget Password",
    login = "Log In",
    signup = "Sign Up",
    createNewAccount = "or, Create a new account?",
    loginWith = "Log In with",
    logout = "Log Out",
    privacyPolicy = "Privacy Policy",
    termsCond = "Terms and Condition",
    alreadyHaveAcc = "Already have an account? ",
    buyYourfav = "Buy Your Favourites",
    welcomeBack = "Welcome Back",
    createNewAcc = "Create An Account",
    loading = "Loading...",
    emptyMail = "Email is empty",
    emptyPass = "Password is empty",
    emptyName = "Name is empty",
    emptyPhone = "Phone number is empty",
    enterDetails = "Enter details",
    home = "Home",
    edit = "Edit",

    //! Cart Strings
    myAccount = "My Account",
    editProfile = "Edit Profile",
    categories = "Categories",
    myCart = "My Cart",
    cart = "Cart",
    orders = "Orders",
    yourOrders = "YOUR ORDERS",
    favorites = "Favorites",
    account = "Account",
    searchAnything = "Search anything...",
    checkout = "Checkout",
    addtoCart = "Add to cart",
    addToCart = "ADD TO CART",
    buynow = "BUY NOW",
    addtoWishlist = "Add to Wishlist",
    removefromWishlist = "Remove from Whishlist",
    itemRemovedfromWishlist = "Item Remove from Wishlist",
    itemAddedtoWishlist = "Item Added to Wishlist",
    addedtoCart = "Added to Cart",
    itemAddedtoCart = "Item Added to Cart",
    removedfromCart = "Removed from Cart",
    itemRemovedfromCart = "Item Removed from Cart",
    yourCartisEmpty = "Your Cart is Empty",
    yourfavouriteisEmpty = "Your favourites is Empty",
    todayDeal = "Today's Deal",
    flashSale = "Flash Sale",
    topSellers = "Top Sellers",
    bestProd = "Best Products",
    brand = "Brand",
    topCategories = "Top Categories",
    featuredCategories = "Featured Categories",
    featuredProduct = "Featured Product",

    //! Shopping Strings
    womenDress = "Women Dress",
    girlsWatch = "Girls Watches",
    mobilePhone = "Mobile Phones",
    boysGlass = "Boys Glasses",
    tShirt = "TShirts",
    girlsDress = "Girls Dress";
